### ISSUE TITLE
error with fix_in_frame_stop_codon_genes.py while using BRAKER-2.1.5

### ISSUE THREAD

**Issue by Aled32** [Gaius-Augustus/Augustus#148]
I am using augustus-3.3.3

error is reproducible

Traceback (most recent call last):
  File "/augustus-3.3.3/scripts/fix_in_frame_stop_codon_genes.py", line 737, in <module>
    for ifs_line in ifs_handle:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 168: ordinal not in range(128)

command:
singularity exec -w braker-sandbox /BRAKER-2.1.5/scripts/braker.pl \
--genome=${byzantina_data}/genomes/subgenomes/byz${sub}.sm.fa \
--prot_seq=${byzantina_data}/byz_GMM_annotation_111119_geneheaders_nostopcodons_fixed.pep.fa \
--bam=${byzantina_data}/bams/ale/byz${sub}_ALL.bam \
--species=byzantina_sub_${sub}_${date} \
--prg=${prg} \
--cores=128 \
--softmasking \
--useexisting \
--workingdir=/BRAKER-2.1.5/tmp/sub_${sub}_${date}

**Comment by tomasbruna** [comment]
Hi @Aled32,

take a look at this issue, it could help: https://github.com/Gaius-Augustus/BRAKER/issues/222

Tomas

**Comment by Aled32** [comment]
I actually traced this problem back to a comment line that Augustus includes in some of its outputs
Notably this line:

`# This output was generated with AUGUSTUS (version 3.3.3).
# AUGUSTUS is a gene prediction tool written by M. Stanke (mario.stanke@uni-greifswald.de),
**# O. Keller, S. König, L. Gerischer, L. Romoth and Katharina Hoff.**
# Please cite: Mario Stanke, Mark Diekhans, Robert Baertsch, David Haussler (2008),
# Using native and syntenically mapped cDNA alignments to improve de novo gene finding
# Bioinformatics 24: 637-644, doi 10.1093/bioinformatics/btn013
# Sources of extrinsic information: M RM E W P C 
# Setting CDSpart lo...`

The character which causes the issue is this one "ö".
To fix this, I added `
                            os.system("sed -i '/^#/d' " + out + "*.out");`
to fix_in_frame_stop_codon_genes.py at line 735, which removes all commented lines from the '.out' files

Its a bit heavy-handed but works for me for now

Thanks,
Aled

**Comment by Aled32** [comment]
Hi Tomas,

I replied to my issue because I found a workaround for this

https://github.com/Gaius-Augustus/Augustus/issues/148

Hope it helps

Best,
Aled
