### ISSUE TITLE
Obsolete Biopython library Bio.Alphabet required in script getAnnoFastaFromJoingenes.py

### ISSUE THREAD

**Issue by BioNica** [Gaius-Augustus/Augustus#200]
Dear authors,

I have recently installed Biopython (biopython-1.78) to complete the requirements for the installation of Augustus and Braker.
By running the pipeline, I came across the following error:

```Traceback (most recent call last):
  File "/tools/AUGUSTUS/augustus-3.3.4/Augustus/scripts/getAnnoFastaFromJoingenes.py", line 35, in <module>
    from Bio.Alphabet import generic_dna, generic_protein
  File "/tools/Biopython/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tools/AUGUSTUS/augustus-3.3.4/Augustus/scripts/getAnnoFastaFromJoingenes.py", line 40, in <module>
    'Failed to import biophython modules. Try installing with \"pip3 install biopython\"')
ImportError: Failed to import biophython modules. Try installing with "pip3 install biopython"
```

Actually, this library has just been removed from Biopython;
https://biopython.org/wiki/Alphabet

Luckily, this site also explains the necessary code changes to adapt for the new style.
I edited just some lines of the script and solved my problem. Here is the diff output:

```### Augustus/scripts/getAnnoFastaFromJoingenes.py
35c35
<     from Bio.Alphabet import generic_dna, generic_protein
---
> #    from Bio.Alphabet import generic_dna, generic_protein
155c155
<                             Seq("", generic_dna), id=tx, description=tx)
---
>                             Seq(""), id=tx, description=tx)
161c161
<                                                      * 'N', generic_dna)
---
>                                                      * 'N')
168,169c168,169
<                                         (3 - (len(codingseq[tx]) % 3)) * 'N',
<                                         generic_dna)
---
>                                         (3 - (len(codingseq[tx]) % 3)) * 'N'
>                                         )
173c173
<                                                          * 'N', generic_dna)
---
>                                                          * 'N')
176,177c176,177
<                                     (3 - (len(codingseq[tx].seq) % 3)) * 'N',
<                                     generic_dna) + codingseq[tx].seq
---
>                                     (3 - (len(codingseq[tx].seq) % 3)) * 'N'
>                                     ) + codingseq[tx].seq
```

Here I share with you the edited file.
https://www.dropbox.com/s/vi2a9hn99yzcyff/getAnnoFastaFromJoingenes.py

I hope this helps.

**Comment by LeebanY** [comment]
Hi, 

I had the same issue. An additional solve is to downgrade biopython to version 1.74. The getAnnoFastaFromJoingenes.py script should work fine then.

**Comment by KatharinaHoff** [comment]
I fixed this in Augustus. Please git pull the Augustus update. https://github.com/Gaius-Augustus/Augustus/commit/34a3ce32cbe48b279fe5e0cff3b3bf113a0d2e9b

Best,

Katharina

**Comment by aabaricalla** [comment]
Hi @KatharinaHoff, I launched the Braker pipeline and have this same issue.

The [Biopython wiki](https://biopython.org/wiki/Alphabet) suggests:

try:
    from Bio.Alphabet import generic_dna
except ImportError:
    generic_dna = None
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio import SeqIO

With this change in the "getAnnoFastaFromJoingenes.py" file, I have no further issues.
I hope this could help others!
