### ISSUE TITLE
Test-data embedded in docs/tutorial2015

### ISSUE THREAD

**Issue by smoe** [Gaius-Augustus/Augustus#242]
Hello,
I do not know the history for this, but for some reason the Debian package does not reditribute the tutorial2015 folder. Seems like I should bring it back in, since
```
$ make test
cd tests/examples && ./testcases.py --compare --html
Removing generated test files...
----------------------------------------------------------------------
Executing small test suite
----------------------------------------------------------------------
ERROR

======================================================================
ERROR: setUpClass (__main__.TestAugustus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/moeller/git/med-team/augustus/tests/examples/./testcases.py", line 260, in setUpClass
    cls.init_test_data()
  File "/home/moeller/git/med-team/augustus/tests/examples/./testcases.py", line 110, in init_test_data
    shutil.copyfile(
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '../../docs/tutorial2015/data/chr2L.sm.fa.gz'

----------------------------------------------------------------------
Ran 0 tests in 0.002s

FAILED (errors=1)
make: *** [Makefile:45: test] Error 1
```
But then again, I am confident that you agree that data that you use for testing should not hide in docs. Instead, I suggest a tests/data directory or so. Have a symlink to it if this helps. ;) Should docs/tutorial* possibly become a repository on its own?

**Comment by satta** [comment]
IIRC I `Files-Excluded` the tutorial and some of the other docs in my first packaging because I was not sure about some of the license of some images etc. that were not provided as source in the tutorial. But I think that was just me being too cautious, I think we can just include them again and have them carried by Debian.

But I agree that test files should live somewhere else :)
